# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errorpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import metapb_pb2 as metapb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='errorpb.proto',
  package='errorpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rerrorpb.proto\x12\x07\x65rrorpb\x1a\x0cmetapb.proto\"<\n\tNotLeader\x12\x11\n\tregion_id\x18\x01 \x01(\x04\x12\x1c\n\x06leader\x18\x02 \x01(\x0b\x32\x0c.metapb.Peer\"B\n\rStoreNotMatch\x12\x18\n\x10request_store_id\x18\x01 \x01(\x04\x12\x17\n\x0f\x61\x63tual_store_id\x18\x02 \x01(\x04\"#\n\x0eRegionNotFound\x12\x11\n\tregion_id\x18\x01 \x01(\x04\"T\n\x0eKeyNotInRegion\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x11\n\tregion_id\x18\x02 \x01(\x04\x12\x11\n\tstart_key\x18\x03 \x01(\x0c\x12\x0f\n\x07\x65nd_key\x18\x04 \x01(\x0c\"8\n\rEpochNotMatch\x12\'\n\x0f\x63urrent_regions\x18\x01 \x03(\x0b\x32\x0e.metapb.Region\"2\n\x0cServerIsBusy\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\x12\n\nbackoff_ms\x18\x02 \x01(\x04\"\x0e\n\x0cStaleCommand\":\n\x11RaftEntryTooLarge\x12\x11\n\tregion_id\x18\x01 \x01(\x04\x12\x12\n\nentry_size\x18\x02 \x01(\x04\"\xad\x03\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12&\n\nnot_leader\x18\x02 \x01(\x0b\x32\x12.errorpb.NotLeader\x12\x31\n\x10region_not_found\x18\x03 \x01(\x0b\x32\x17.errorpb.RegionNotFound\x12\x32\n\x11key_not_in_region\x18\x04 \x01(\x0b\x32\x17.errorpb.KeyNotInRegion\x12/\n\x0f\x65poch_not_match\x18\x05 \x01(\x0b\x32\x16.errorpb.EpochNotMatch\x12-\n\x0eserver_is_busy\x18\x06 \x01(\x0b\x32\x15.errorpb.ServerIsBusy\x12,\n\rstale_command\x18\x07 \x01(\x0b\x32\x15.errorpb.StaleCommand\x12/\n\x0fstore_not_match\x18\x08 \x01(\x0b\x32\x16.errorpb.StoreNotMatch\x12\x38\n\x14raft_entry_too_large\x18\t \x01(\x0b\x32\x1a.errorpb.RaftEntryTooLargeR\x0bstale_epochb\x06proto3')
  ,
  dependencies=[metapb__pb2.DESCRIPTOR,])




_NOTLEADER = _descriptor.Descriptor(
  name='NotLeader',
  full_name='errorpb.NotLeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region_id', full_name='errorpb.NotLeader.region_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leader', full_name='errorpb.NotLeader.leader', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=100,
)


_STORENOTMATCH = _descriptor.Descriptor(
  name='StoreNotMatch',
  full_name='errorpb.StoreNotMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_store_id', full_name='errorpb.StoreNotMatch.request_store_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actual_store_id', full_name='errorpb.StoreNotMatch.actual_store_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=168,
)


_REGIONNOTFOUND = _descriptor.Descriptor(
  name='RegionNotFound',
  full_name='errorpb.RegionNotFound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region_id', full_name='errorpb.RegionNotFound.region_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=205,
)


_KEYNOTINREGION = _descriptor.Descriptor(
  name='KeyNotInRegion',
  full_name='errorpb.KeyNotInRegion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='errorpb.KeyNotInRegion.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='errorpb.KeyNotInRegion.region_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_key', full_name='errorpb.KeyNotInRegion.start_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_key', full_name='errorpb.KeyNotInRegion.end_key', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=291,
)


_EPOCHNOTMATCH = _descriptor.Descriptor(
  name='EpochNotMatch',
  full_name='errorpb.EpochNotMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_regions', full_name='errorpb.EpochNotMatch.current_regions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=349,
)


_SERVERISBUSY = _descriptor.Descriptor(
  name='ServerIsBusy',
  full_name='errorpb.ServerIsBusy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='errorpb.ServerIsBusy.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backoff_ms', full_name='errorpb.ServerIsBusy.backoff_ms', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=401,
)


_STALECOMMAND = _descriptor.Descriptor(
  name='StaleCommand',
  full_name='errorpb.StaleCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=417,
)


_RAFTENTRYTOOLARGE = _descriptor.Descriptor(
  name='RaftEntryTooLarge',
  full_name='errorpb.RaftEntryTooLarge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region_id', full_name='errorpb.RaftEntryTooLarge.region_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entry_size', full_name='errorpb.RaftEntryTooLarge.entry_size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=477,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='errorpb.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='errorpb.Error.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='not_leader', full_name='errorpb.Error.not_leader', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region_not_found', full_name='errorpb.Error.region_not_found', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_not_in_region', full_name='errorpb.Error.key_not_in_region', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_not_match', full_name='errorpb.Error.epoch_not_match', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_is_busy', full_name='errorpb.Error.server_is_busy', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stale_command', full_name='errorpb.Error.stale_command', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='store_not_match', full_name='errorpb.Error.store_not_match', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raft_entry_too_large', full_name='errorpb.Error.raft_entry_too_large', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=909,
)

_NOTLEADER.fields_by_name['leader'].message_type = metapb__pb2._PEER
_EPOCHNOTMATCH.fields_by_name['current_regions'].message_type = metapb__pb2._REGION
_ERROR.fields_by_name['not_leader'].message_type = _NOTLEADER
_ERROR.fields_by_name['region_not_found'].message_type = _REGIONNOTFOUND
_ERROR.fields_by_name['key_not_in_region'].message_type = _KEYNOTINREGION
_ERROR.fields_by_name['epoch_not_match'].message_type = _EPOCHNOTMATCH
_ERROR.fields_by_name['server_is_busy'].message_type = _SERVERISBUSY
_ERROR.fields_by_name['stale_command'].message_type = _STALECOMMAND
_ERROR.fields_by_name['store_not_match'].message_type = _STORENOTMATCH
_ERROR.fields_by_name['raft_entry_too_large'].message_type = _RAFTENTRYTOOLARGE
DESCRIPTOR.message_types_by_name['NotLeader'] = _NOTLEADER
DESCRIPTOR.message_types_by_name['StoreNotMatch'] = _STORENOTMATCH
DESCRIPTOR.message_types_by_name['RegionNotFound'] = _REGIONNOTFOUND
DESCRIPTOR.message_types_by_name['KeyNotInRegion'] = _KEYNOTINREGION
DESCRIPTOR.message_types_by_name['EpochNotMatch'] = _EPOCHNOTMATCH
DESCRIPTOR.message_types_by_name['ServerIsBusy'] = _SERVERISBUSY
DESCRIPTOR.message_types_by_name['StaleCommand'] = _STALECOMMAND
DESCRIPTOR.message_types_by_name['RaftEntryTooLarge'] = _RAFTENTRYTOOLARGE
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotLeader = _reflection.GeneratedProtocolMessageType('NotLeader', (_message.Message,), dict(
  DESCRIPTOR = _NOTLEADER,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.NotLeader)
  ))
_sym_db.RegisterMessage(NotLeader)

StoreNotMatch = _reflection.GeneratedProtocolMessageType('StoreNotMatch', (_message.Message,), dict(
  DESCRIPTOR = _STORENOTMATCH,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.StoreNotMatch)
  ))
_sym_db.RegisterMessage(StoreNotMatch)

RegionNotFound = _reflection.GeneratedProtocolMessageType('RegionNotFound', (_message.Message,), dict(
  DESCRIPTOR = _REGIONNOTFOUND,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.RegionNotFound)
  ))
_sym_db.RegisterMessage(RegionNotFound)

KeyNotInRegion = _reflection.GeneratedProtocolMessageType('KeyNotInRegion', (_message.Message,), dict(
  DESCRIPTOR = _KEYNOTINREGION,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.KeyNotInRegion)
  ))
_sym_db.RegisterMessage(KeyNotInRegion)

EpochNotMatch = _reflection.GeneratedProtocolMessageType('EpochNotMatch', (_message.Message,), dict(
  DESCRIPTOR = _EPOCHNOTMATCH,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.EpochNotMatch)
  ))
_sym_db.RegisterMessage(EpochNotMatch)

ServerIsBusy = _reflection.GeneratedProtocolMessageType('ServerIsBusy', (_message.Message,), dict(
  DESCRIPTOR = _SERVERISBUSY,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.ServerIsBusy)
  ))
_sym_db.RegisterMessage(ServerIsBusy)

StaleCommand = _reflection.GeneratedProtocolMessageType('StaleCommand', (_message.Message,), dict(
  DESCRIPTOR = _STALECOMMAND,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.StaleCommand)
  ))
_sym_db.RegisterMessage(StaleCommand)

RaftEntryTooLarge = _reflection.GeneratedProtocolMessageType('RaftEntryTooLarge', (_message.Message,), dict(
  DESCRIPTOR = _RAFTENTRYTOOLARGE,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.RaftEntryTooLarge)
  ))
_sym_db.RegisterMessage(RaftEntryTooLarge)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'errorpb_pb2'
  # @@protoc_insertion_point(class_scope:errorpb.Error)
  ))
_sym_db.RegisterMessage(Error)


# @@protoc_insertion_point(module_scope)
